-- New, empty PostgreSQL schema only. Legacy MySQL V1-V4 remain unchanged.
-- Timestamps represent UTC; booking dates are interpreted in Asia/Seoul.
CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 login_id VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 name VARCHAR(30) NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL,
 signup_note VARCHAR(500), auth_version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6)
);
CREATE TABLE invite_codes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(100) NOT NULL UNIQUE, status VARCHAR(20) NOT NULL,
 expires_at TIMESTAMP(6) NOT NULL, used_by_user_id BIGINT, created_by BIGINT NOT NULL,
 created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6)
);
CREATE TABLE villa_schedule_lock (id BIGINT PRIMARY KEY);
INSERT INTO villa_schedule_lock(id) VALUES (1);
CREATE TABLE admin_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 actor_id BIGINT, action VARCHAR(40) NOT NULL, target_id BIGINT,
 reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE password_reset_tokens (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id), token_hash VARCHAR(64) NOT NULL UNIQUE,
 expires_at TIMESTAMP(6) NOT NULL, used_at TIMESTAMP(6)
);
CREATE TABLE reservations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 start_date DATE NOT NULL, end_date DATE NOT NULL, guest_count INT NOT NULL,
 memo VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, policy_version VARCHAR(20) NOT NULL,
 request_key VARCHAR(100) NOT NULL, request_hash VARCHAR(64) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
 UNIQUE(user_id,request_key), CHECK(start_date <= end_date), CHECK(guest_count > 0)
);
CREATE INDEX ix_reservation_user ON reservations(user_id,status,start_date);
CREATE INDEX ix_reservation_calendar ON reservations(status,start_date);
CREATE TABLE calendar_blocks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 start_date DATE NOT NULL, end_date DATE NOT NULL,
 reason VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_by BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMP(6) NOT NULL, CHECK(start_date <= end_date)
);
CREATE TABLE calendar_occupancy (
 use_date DATE PRIMARY KEY, reservation_id BIGINT REFERENCES reservations(id),
 block_id BIGINT REFERENCES calendar_blocks(id),
 CHECK((reservation_id IS NOT NULL AND block_id IS NULL)
    OR (reservation_id IS NULL AND block_id IS NOT NULL))
);
CREATE TABLE reservation_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reservation_id BIGINT NOT NULL REFERENCES reservations(id),
 actor_id BIGINT NOT NULL REFERENCES users(id), action VARCHAR(30) NOT NULL,
 reason VARCHAR(500) NOT NULL, before_value VARCHAR(1000),
 after_value VARCHAR(1000) NOT NULL, created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX ix_history_reservation ON reservation_history(reservation_id,created_at);
CREATE TABLE communication_tasks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 history_id BIGINT NOT NULL UNIQUE REFERENCES reservation_history(id),
 recipient_id BIGINT NOT NULL REFERENCES users(id),
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 contacted_at TIMESTAMP(6), acknowledged_at TIMESTAMP(6)
);
