# ===============================
# SERVER
# ===============================
server.port=61228

# ===============================
# DATASOURCE (MySQL)
# 실제 민감 정보는 application-secret.properties 에 저장중
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# ===============================
# JWT
# 실제 민감 정보는 application-secret.properties 에 저장중
# ===============================
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000

# ===============================
# SECRET CONFIG IMPORT
# ===============================
spring.config.import=optional:application-secret.properties