apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: std20-mysql-statefulset
spec:
  serviceName: "std20-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: std20-mysql
  template:
    metadata:
      labels:
        app: std20-mysql
    spec:
      containers:
      - name: std20-mysql-containe
        image: mysql:8.0
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "melt7542"

        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          hostPath:
            path: /tmp/mysql-data
            type: DirectoryOrCreate