CREATE TABLE users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, login_id VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL, name VARCHAR(30) NOT NULL,
 role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, signup_note VARCHAR(500),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6)
);
CREATE TABLE invite_codes (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE,
 status VARCHAR(20) NOT NULL, expires_at DATETIME(6) NOT NULL,
 used_by_user_id BIGINT, created_by BIGINT NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6)
);
