ALTER TABLE users ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) NOT NULL;
ALTER TABLE users MODIFY COLUMN status VARCHAR(20) NOT NULL;
ALTER TABLE invite_codes MODIFY COLUMN status VARCHAR(20) NOT NULL;
CREATE TABLE villa_schedule_lock (id BIGINT PRIMARY KEY);
INSERT INTO villa_schedule_lock(id) VALUES (1);
CREATE TABLE admin_audit (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, actor_id BIGINT, action VARCHAR(40) NOT NULL,
 target_id BIGINT, reason VARCHAR(1000) NOT NULL, created_at DATETIME(6) NOT NULL
);
CREATE TABLE password_reset_tokens (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL,
 token_hash VARCHAR(64) NOT NULL UNIQUE, expires_at DATETIME(6) NOT NULL, used_at DATETIME(6),
 FOREIGN KEY (user_id) REFERENCES users(id)
);
